import React, { useEffect } from 'react';
import style from "./UserTerm.module.css";
import { Button, Heading, ListItem, Text, UnorderedList } from '@chakra-ui/react';
import { FaFileDownload } from 'react-icons/fa';


const UserTerm = () => {

    useEffect(() => {
        // 👇️ scroll to top on page load
        window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
    }, []);

    return (
        <div className={style.userterm}>
            <div className={style.download_btn}>
                <Button rightIcon={<FaFileDownload />} colorScheme='blue' variant='outline'>
                    download
                </Button>
            </div>
            <Heading as={"h2"} size={"md"}>INTRODUCTION</Heading>
            <Text>This website assetorix.com, including any subdomains thereof, and any other websites through which its services are made available, our mobile, tablet and other smart device applications, and application program interfaces etc, , (hereinafter collectively referred to as " assetorix.com ") is owned, hosted and operated by Ametheus Holdings Pvt Ltd (hereinafter referred to as AHPL), a company incorporated in India under the Companies Act, 1956 and having its registered office at 27, 2nd Floor, Hauz Khas Village, New Delhi - 110016. These user terms and conditions, privacy policy and payment terms & conditions guidelines regulating use of these Services constitute a legally binding agreement between assetorix.com and the User (the “Agreement”).
            </Text>
            <Text>
                assetorix.com and/or any other website(s) linked to this website is an online information and communications service provided to you, subject to your compliance with the terms and conditions set forth below.
            </Text>
            <Text>
                AHPL may amend/modify these terms and conditions at any time, and such modifications shall be effective immediately upon posting of the modified terms and conditions on assetorix.com You may review the modified terms and conditions periodically to be aware of such modifications and your continued access or use of assetorix.com, shall be deemed conclusive proof of your acceptance of these terms and conditions, as amended/modified from time to time. AHPL may also suspend the operation of assetorix.com for support or technical upgradation, maintenance work, in order to update the content or for any other reason.
                If you utilize assetorix.com in a manner inconsistent with these terms and conditions, AHPL may terminate your access, block your future access and/or seek such additional relief as the circumstances of your misuse may be deemed to be fit and proper.
            </Text>
            <Heading as={"h2"} size={"md"}>GENERAL INFORMATION</Heading>
            <Text>
                a) This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </Text>
            <Text>
                b) This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Guidelines for Intermediaries and Digital Media Ethics Code) Rules, 2021 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the website assetorix.com and the mobile application assetorix (together, “Website”).
            </Text>
            <Text>
                c) The Website, is owned and operated by Ametheus Private Limited ("Company") a private company limited by shares, incorporated under the provisions of the Companies Act, 2013, and having its registered office at 27, 2nd Floor, Hauz Khas Village, New Delhi 110016, India. The expression “Company” shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents, successors and assigns.
            </Text>
            <Text>d) For the purpose of these Terms of Use ("Terms"):</Text>
            <Text>
                The term 'you' & 'user' shall mean any natural or legal person or entity accessing or using the services provided on this Website, who is competent to enter into binding contracts, as per the provisions of the Indian Contract Act, 1872, or, has not otherwise been barred by any applicable law for the time being in force from entering into contracts;
            </Text>
            <Text>
                The terms 'We', 'Us' & 'Our' shall mean the Website and/or the Company, as the context may require.
            </Text>
            <Text>
                The terms 'Party' & 'Parties' shall refer to the User and the Company individually and collectively, as the context may require.
            </Text>
            <Text>
                e) The headings of each section in these Terms are only for the purpose of organizing the various provisions under these Terms in an orderly manner and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.
            </Text>
            <Text>
                f) The use of the Website by the User is solely governed by these Terms as well as the Privacy Policy ("Policy" or “Privacy Policy”), available at https://assetorix.com/privacy , and any modifications or amendments made thereto by the Company from time to time, at its sole discretion. Visiting the Website and/or using any of the services provided on the Website shall be deemed to signify the User's unequivocal acceptance of these Terms and the aforementioned Policy, and the User expressly agrees to be bound by the same. The User expressly agrees and acknowledges that the Terms and Policy are co-terminus, and that expiry / termination of either one will lead to the termination of the other, save as provided in Section 3 hereunder.
            </Text>
            <Text>
                g) The User unequivocally agrees that these Terms and the aforementioned Policy constitute a legally binding agreement between the User and the Company, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Website, and that the same shall be deemed to be incorporated into these Terms and shall be treated as part and parcel of the same. The User acknowledges and agrees that no signature or express act is required to make these Terms and the Policy binding on the User, and that the User's act of visiting the any part of the Website or use of the services provided through the Website constitutes the User's full and final acceptance of these Terms and the aforementioned Policy.
            </Text>
            <Text>
                h) The Company reserves the sole and exclusive right to amend or modify these Terms without any prior permission or intimation to the User, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. Where material changes are made to these Terms or the Policy, or if deemed appropriate by us, the User will be notified of such material upon accessing the Website. Notwithstanding the foregoing, the User acknowledges and agrees to its duty to periodically check the terms and stay updated on its requirements. If the User continues to use the Website following such a change, the User will be deemed to have consented to any and all amendments/modifications made to the Terms. In so far as the User complies with these Terms, he/she is granted a personal, non-exclusive, non-transferable, revocable, and limited right and privilege to enter and use the Website.
            </Text>
            <Heading as={"h2"} size={"md"}>
                The Services:</Heading>
            <Text>
                The Website is an online listing and transaction platform, that provides an end-to-end solution to real estate buyers and recommends real estate properties across the globe in accordance with the requirements of its customers. The Company, through the Website, facilitates professional consultancy and offers 360-degree services towards real estate investments. Below mentioned are the list of services provided on the Website (“Services”):
            </Text>
            <Text>
                Property Identification- We provide to our customers, the facility of searching (from the extensive real estate portfolio available on our Website) and finalizing property by making use of a combination of digital and expert solutions to re-engineer the process of purchasing or leasing properties. Our services are offered, and the Website operates with the aim to meet the specific requirements of our customers. The Website hosts details of a large array of properties listed by real estate developers with whom the Company partners in order to provide efficient services and a seamless purchase/leasing experience to the customers.
            </Text>
            <Text>
                Transactional Support – Our sales team assists the customers with site visits (physical and virtual), property comparison and pricing / inventory negotiation.
            </Text>
            <Text>
                Financial & Administrative Support – Our dedicated team aids and assists the customer in finding leads pertaining to mortgage, loan & other financial services (which are rendered by banking and other financial institutions) as well as virtual administrative & legal support (through consultants and advisors with whom the Company has partnered).
            </Text>
            <Text>
                Other Allied Services - The Company facilitates for its customers, through its various business partners, services pertaining to packing, moving, interior designing, furnishing, etc.
            </Text>
            <Text>
                Product Portfolio - Our real estate portfolio covers a large domain of properties and we cater to all kinds of properties including residential (primary & resale), commercial, leasing, land, global projects, affordable housing, investor projects, structured offerings etc.
            </Text>
            <Text>
                Portfolio Structuring & Management- We help diversify our clients' real estate portfolios around the globe and are pioneers in bringing Global Properties with the best payout options to Indian investors.
            </Text>
            <Text>
                Service for Life – We may assign a "Dedicated Relationship Manager" for customer assistance for life.
            </Text>
            <Heading as={"h2"} size={"md"}>ELIGIBILITY</Heading>
            <Text>
                The User represents and warrants that he/she is competent and eligible to enter into legally binding agreements and that he/she has the requisite authority to bind himself/herself to these Terms, as determined solely by the provisions of the Indian Contract Act, 1872. The User may not use this Website if he/she is not competent to contract under the Indian Contract Act, 1872, or is disqualified from doing so by any other applicable law, rule or regulation currently in force.
            </Text>
            <Heading as={"h2"} size={"md"}>USER REGISTRATION AND USER CONTENT</Heading>
            <Text>
                a) The User agrees that, in order to access and use the Services, he/she will have to create an account on the Website and provide certain personally identifiable information to the Company such as name, username, email address, postal address, telephone/mobile number and other information as may be requested by the Company.
            </Text>
            <Text>
                b) By registering and creating an account on the Website, the User shall be responsible for maintaining confidentiality of his/her login credentials (login name, password), financial information and for all activities that occur through his/her account. The User agrees that all the information provided by him/her to the Company is true, accurate and complete. If any information provided by a User is inconsistent, inaccurate, not current or incomplete, and if the Company has reasonable grounds to suspect that such information is inconsistent, inaccurate, not current or incomplete, or not in accordance with these Terms or policies referred to herein, the Company reserves the right to indefinitely suspend, block access or terminate his/her registration with the Company through the Website, at its sole discretion, without providing any reason and without the liability to make any payment to the User. The Company is also not responsible for the accuracy, usefulness or efficiency of any Services based on incorrect, inaccurate, not current or incomplete information furnished by a User.
            </Text>
            <Text>
                c) In addition to the information mentioned above, the Website may require the Users to provide content (such as comments, ideas, suggestions, initiation, or any other content contributed by the User) in form of text, graphics, user interfaces, visual interfaces, photographs and sounds, video content generate in pursuance of use of the Services provided by the Website. The Website also may also request a response on the questionnaire or feedback from the Users (together the “User Content”). The User warrants that he/she shall upload/provide the accurate and complete User Content to the Website. The User Content posted by Users is the sole responsibility of the User and the Company is not responsible for, or liable in any manner, for such User Content and disclaims all liability arising from inaccuracy of the User Content.
            </Text>
            <Text>
                d) To the extent User Content is shared with the Company, the User grants the Company a fully transferable, royalty-free, perpetual, sub-licensable, non-exclusive, worldwide license to copy, distribute, modify or create derivative works based on, display, and otherwise use the User Content.
            </Text>
            <Text>
                e) In particular, the Company may use the User Content for research and development to improve or modify the Services, in which case the User shall have no right, title or interest in such improved or modified Services. The Company reserves the right to use or modify User Content licensed to it, without providing the User with reason or notice.
            </Text>
            <Text>
                f) The User hereby represents and warrants that he/she owns or otherwise controls all of the rights to the content contributed to the Website, and that use of such content by the Company/Website does not infringe upon or violate the rights of any third party. In the event of any action initiated against the Company/Website by any such affected third party, the User hereby expressly agrees to indemnify and hold harmless the Company/Website, for its use of any such information provided to it by the User. The Company reserves its right to defend itself in any such legal disputes that may arise, and recover the costs incurred in such proceedings from the User. The Company shall have the right to remove or edit any User Content that, in its sole discretion, violates, or is alleged to violate, any applicable law or either the express terms or intent of these Terms.
            </Text>
            <Text>
                g) Notwithstanding this right, the User shall remain solely responsible for the content and the materials they post on the Website and in their private/public messages.
            </Text>
            <Heading as={"h2"} size={"md"}>
                TERMINATION
            </Heading>
            <Text>
                a) The Company reserves the right, in its sole discretion, to unilaterally terminate the User's access to the Services offered on the Website, or any portion thereof, at any time, without notice or cause. The User acknowledges and agrees that the Company may immediately deactivate or delete his/her account and all related information and files in his/her account and/or bar any further access to such files or the Website and related Services.
            </Text>
            <Text>
                b) Without prejudice to generality of Section 4(a) above, the Company may, at its sole discretion suspend or terminate a User’s account (or any part thereof) or his/her use of the Services, and remove and discard any content within the Services, for any reason, including, without limitation, for lack of use, or if the Company believes that he/she has violated or acted inconsistently with any of its Terms or policies, referred to herein.
            </Text>
            <Text>
                c) Any suspected fraudulent, abusive or illegal activity that may be grounds for immediate termination of a User’s use and access of the Website and Services and may also be referred to appropriate law enforcement authorities.
            </Text>
            <Text>
                e) The Company may, at any time and at its sole discretion, reinstate suspended Users. A User that has been suspended or blocked may not register or attempt to register with us or use the Website in any manner whatsoever, until such time that such User is reinstated by the Company.
            </Text>
            <Text>
                f) Notwithstanding the foregoing, in the event of any breach of these Terms or the Privacy Policy or other rules and/or policies of the Company, the Company reserves the right to recover any amounts due and owing by the User and/or take strict legal action including but not limited to, a referral to the appropriate police, or other authorities, and/or for initiating criminal or other proceedings against the User.
            </Text>
            <Text>
                g) The User agrees that the Company will not be liable to the User, or any third party, for any termination of his/her access to the Website.
            </Text>
            <Text>
                The User shall continue to be bound by these Terms, and it is expressly agreed to by the Parties that the User shall not have the right to terminate these Terms till the expiry of the same, except as described in Section 4 hereinabove.
            </Text>
            <Heading as={"h2"} size={"md"}>
                COMMUNICATION
            </Heading>
            <Text>
                By using this Website and providing his/her contact information to the Company through the Website, the User hereby agrees and consents to receiving calls, auto-dialed and/or pre-recorded message calls, e-mails and SMSs from the Company and/or any of its affiliates or partners at any time, subject to the Policy. In the event that the User wishes to stop receiving any such marketing or promotional calls / email messages / text messages, the User may send an email to the effect to hello@assetorix.xyz with the subject “Unsubscribe”. The User agrees and acknowledges that it may take up to seven (7) business days for the Company to give effect to such a request by the User.
            </Text>
            <Text>
                The User expressly agrees that notwithstanding anything contained herein above, he/she may be contacted by the Company or any of its affiliates / partners relating to any service availed of by the User on the Website or anything pursuant thereto.
            </Text>
            <Text>
                It is expressly agreed to by the Parties that any information shared by the User with the Company shall be governed by the Policy.
            </Text>
            <Heading as={"h2"} size={"md"}>CHARGES</Heading>
            <Text>
                The use of this Website by the User, such as browsing the Website is free of cost. The User is only required to pay for the Services availed by the User of the Website. Payments for the Services offered by assetorix.com shall be on a 100% advance basis. The payment for Service once subscribed to by the subscriber is not refundable and any amount paid shall stand appropriated. Refund if any will be at the sole discretion of Ametheus Holdings Pvt Ltd (AHPL). AHPL offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the Users card/bank accounts. User acknowledges and agrees that AHPL/ assetorix.com, at its sole discretion and without prejudice to other rights and remedies that it may have under the applicable laws, shall be entitled to set off the amount paid or payable by a subscriber/user against any amount(s) payable by User to AHPL under any other agreement or commercial relationship towards other products/services. Ametheus Holdings Pvt Ltd gives no guarantees of server uptime or applications working properly. All is on a best effort basis and liability is limited to refund of amount only.
            </Text>
            <Text>
                Ametheus Holdings Pvt Ltd (AHPL)/ assetorix.com reserves the right to amend this no-fee policy and charge the User for any or all Services offered / rendered by it, including fee for accessing the Website. Ametheus Holdings Pvt Ltd reserves its right to amend / alter or change all or any disclaimers or terms of agreements at any time without any prior notice. All terms / disclaimers whether specifically mentioned or not shall be deemed to be included if any reference is made to them. In such an event, the User will be intimated of the same when he/she attempts to access the Website, and the User shall have the option of declining to avail the Services offered on the Website. Any such change, if made, shall come into effect immediately upon such change being notified to the User, unless specified otherwise.
            </Text>
            <Text>
                The Company may, in respect of a property listed on the Website or any other services facilitated through the Website, and for the duration prior to completion of sale/lease of property or completion of the services opted by the User, require the Users to pay a token amount which will be held by the Company on behalf of the real estate developers/ service providers with whom the User has engaged through the Website in an escrow account which is held in the name of the real estate developers/ service providers (“Escrow Account”) with whom the User has engaged through the Website. The payment to this Escrow Account, shall be facilitated by a payment gateway service provider, which service provider shall be specified on the Website. Such token amount shall, upon finalization of sale/lease of property or provision of any service by a business partner, be adjustment in the consideration payable by the Users to real estate developers/ service providers for the property purchased/ or services taken, as the case may be. The Company shall be entitled to deduct its service fees from the amounts intended to be deposited into the Escrow Account. Where no sale/lease of property occurs, or no services are rendered (due to no fault of the User),the Company shall liaise with the real estate developers/ service providers who/which holds the Escrow Account for the refund of the token amount to the User. It is clarified that, the Company shall not be liable to pay any amounts that have been transferred by the User into the Escrow Account, in any circumstance whatsoever. Refund of the token amount received into the Escrow Account shall be the responsibility of the real estate developers/ service providers with whom the User has engaged through the Website and who/which person holding the Escrow Account. The Company is not in control of the Escrow Account and does not own the Escrow Account, therefore the Company will not be responsible for any delay or improper refund of the token amounts.
            </Text>
            <Text>
                Where a User takes a loan from or otherwise makes use of financial assistance/aid provided by any banking/financial institution that are listed or linked on the Platform for purchase/lease or any property listed on the Website or for taking any other services facilitated by the Website, such financial institution may, in accordance with terms and conditions of its own services as well as in accordance with applicable laws, remit the money to the real estate developer or other service provider concerned. The manner of flow of monies shall be such as is determined by such banking or financial institutions and the Company shall have no responsibility, obligation or liability, whether direct or indirect, in respect of the same.
            </Text>
            <Text>
                Ametheus Holdings Pvt Ltd uses the maximum care as is possible to ensure that all or any data / information in respect of electronic transfer of money does not fall in the wrong hands. For completing online transactions involving payments a user is directed to a Payment Gateway, Ametheus Holdings Pvt Ltd does not store or keep credit card data. Since the transaction happens on a third-party network not controlled by Ametheus Holdings Pvt Ltd, once a credit card transaction has been completed, the payment information is not accessible to anyone at Ametheus Holdings Pvt Ltd after completion of the on-line transaction at the Payment Gateway, this ensures the maximum security.
            </Text>
            <Text>
                Ametheus Holdings Pvt Ltd shall not be liable for any loss or damage sustained by reason of any disclosure (inadvertent or otherwise) of any information concerning the user's account and / or information relating to or regarding online transactions using credit cards / debit cards and / or their verification process and particulars nor for any error, omission or inaccuracy with respect to any information so disclosed and used whether or not in pursuance of a legal process or otherwise.
            </Text>
            <Heading as={"h2"} size={"md"} >REFUND IN FAILED TRANSACTIONS</Heading>
            <Text>
                Though AHPL payment reconciliation team works on a 24 x 7 basis, AHPL offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the Subscribers card/bank accounts. This is on account of the multiplicity of organizations involved in processing of online transactions, the problems with Internet infrastructure currently available and working days/holidays of financial institutions. Refunds in the event of wrong/objectionable property content being posted on the site would be at the discretion of assetorix.com.
                <br />
                If you utilize assetorix.com in a manner inconsistent with these terms and conditions, AHPL may terminate your access, block your future access and/or seek such additional relief as the circumstances of your misuse may be deemed to be fit and proper.
            </Text>
            <Text>
                Rental property services terms
            </Text>
            <Text>
                The Rental Property Services shall not be used for any purpose other than payment of or charging rent or for preparing and registering rental agreement and User not transmit any information received through the Rental Property Services to third parties. All responsibility for information furnished and its accuracy shall reside upon the User, and the User shall be liable for any liability incurred and shall hold assetorix.com or its affiliates and employees harmless against any claim or action by any person/financial institution/regulatory bodies. By utilizing this service User agrees that assetorix.com may share the information provided to third parties for processing on the User’s behalf, as may be required from time to time. User shall not submit any false or fraudulent information through any of the Services offered.
            </Text>
            <Heading as={"h2"} size={"md"}>Rental payment</Heading>
            <Text>
                The Rental Property Services shall not be used for any purpose other than payment of or charging rent or for preparing and registering rental agreement and User does not transmit any information received through the Rental Property Services to third parties. All responsibility for information furnished and its accuracy shall reside upon the User, and the User shall be liable for any liability incurred and shall hold assetorix.com or its affiliates and employees harmless against any claim or action by any person/financial institution/regulatory bodies. By utilizing this service User agrees that assetorix.com may share the information provided to third parties for processing on the User’s behalf, as may be required from time to time. User shall not submit any false or fraudulent information through any of the Services offered.
            </Text>
            <Text>
                By making payment, User provides an authorization to assetorix.com to hold, receive and disburse funds in accordance with the User’s payment instructions provided through assetorix.com for the purposes of facilitating the transfer of money to the intended beneficiary as specified by the User. In the event the processing of transaction is affected due to incomplete/incorrect details being furnished by the User, assetorix.com reserves the right to deduct any applicable service charge, processing fees, or any other fees incurred by it in the processing of this transaction. assetorix.com or its affiliates and employees shall not be responsible for any incorrect/unintended transaction, in any form or manner. assetorix.com may, depending on the security or financial risk associated with the transaction, delay, suspend or reject a transaction.
            </Text>
            <Text>
                The amount of a transaction may be charged back (hereinafter referred as “Chargeback”) if the transaction is disputed, reversed or not authorized, is unlawful or not in accordance with these terms (e.g. the holder of the payment instrument used for initiating the transaction raises a dispute). In case of a Chargeback, User shall immediately pay any amount owed, including additional fines or penalties levied in this regard by the payment gateway or issuer. User agrees to provide complete assistance in the event of any investigation in this regard.
            </Text>
            <Heading as={"h2"} size={"md"}>
                MODE OF PAYMENT
            </Heading>
            <Text>
                This section pertains to the payments made by the User for the Services rendered by the Company.
            </Text>
            <Text>
                a) The following payment options are available on the Website:
            </Text>
            <Text>
                Domestic and international credit cards issued by banks and financial institutions that are part of the Gpay, PayTM, Paypal, Stripe, Rupay, Visa, Mastercard & Amex Card networks.
            </Text>
            <Text>
                Visa & Mastercard Debit cards.
                <br />
                Netbanking /Direct Debit payments from select banks in India. A list of acceptable banks will be made available at the time of 'checkout';
                <br />
                Third-party payment wallets (as listed at the time of ‘checkout’) any other payment system/option approved by the Reserve Bank of India.
                <br />
                b) As prescribed by the financial institutions issuing the credit or debit cards affiliated with Rupay / Visa / Master Card / Amex, the User will be required to submit his/her 16-digit card number, card expiry date and 3-digit CVV number (usually on the reverse of the card) while making an online transaction. The User must also have enrolled his/her card with VBV (Verified by Visa) or MSC (MasterCard Secure Code) in order to complete the transaction. The User is hereby expressly made aware that his/her card statements will reflect that a payment has been made in favour of the Company. To the extent payment is made from third party payment wallets or payment banks account or any like intermediary, the User will be redirected to the website/mobile application of such payment wallet/payment banks/payment intermediary where the User maintains an account and all deductions made therefrom will be subject to terms and conditions of such third-party payment wallet/payment banks/payment intermediary. The Company shall not, in any manner whatsoever, be responsible for use and operation of such accounts of the User maintained with payment wallet/payment bank account/payment intermediary or for any deductions made from such account. A payment to the Company, with respect to the services rendered by it, will be considered complete only when the same is reflected in the bank account of the Company and the Company will not be liable for any deductions made from the User’s payment accounts (howsoever maintained) but which has not reached the accounts of the Company. To place a valid order on the Website, the User is required to complete the transaction, including making payment for the Services opted for. This may or may not be assisted with a phone call from a customer service representative. By placing an order on the site or over the phone, the User expressly agrees to the terms and conditions and payment policy published in the appropriate section of the Website, or affiliated websites where reference to such affiliated websites has been specifically made.
            </Text>
            <Text>
                c) After the User makes his request for the service the User will be asked for his contact information and payment related information. The User categorically authorizes the Company to collect, process, facilitate and remit payments electronically from the User’s bank or credit card company, in the event a User purchases the Services from the Website. Once the payment transaction has been successfully completed, the user's order will be processed on receipt of the funds from the User's bank or credit card company. It is at this stage that the User's order is successfully placed. Thereafter necessary steps will be taken to execute the order.
            </Text>
            <Text>
                d) The User understands, accepts and agrees that the payment facilities provided/used by the Company are neither banking nor financial services but merely serve the role of a facilitator, providing electronic, automated and/or online payment infrastructure. The Company receives money through for transactions envisioned on the Website, through existing authorized banking infrastructure and credit cards service providers. Further, by providing these payment facilities, the Company neither acts as a trustee nor does it assume any fiduciary responsibility with respect to the transactions processed by the User.
            </Text>
            <Text>
                e) While availing any of the payment method(s) available on the Website, the Company will not be responsible or assume any liability whatsoever, in respect of any loss or damage arising directly or indirectly to a User due to:
            </Text>
            <Text>
                lack of authorization for any transaction/s, or <br />
                exceeding the limit mutually agreed by the User with his/her bank, or <br />
                any payment issues arising out of the transaction, or <br />
                decline of the transaction for any other reason/s. <br />
                f) The Company may, at its sole discretion, introduce new services or features and modify some or all existing Services offered on the Website. In such event, the Company reserves the right to introduce fees for the new services offered, or amend/introduce fees for existing Services, as the case may be.
            </Text>
            <Text>
                It is clarified that, any payment of the token amount to be credited into the Escrow Account as per section 7 above, shall be made through a payment gateway service provider and the payment options provided by such payment gateway service provider.
            </Text>
            <Heading as={"h2"} size={"md"}>VOUCHER & GIFT CARD</Heading>
            <Text>
                Any voucher issued from any company is valid only upon registration of the property in assetorix.com.
            </Text>
            <Text>
                Ametheus Holdings Pvt Ltd (AHPL) / Assetorix.com takes no responsibility of durables purchased using the Ikea vouchers.
                <br />
                Vouchers are valid until one year from the date of issuance and can be redeemed at any store of the voucher issuing company in India.
                <br />
                These vouchers are non-refundable and cannot be exchanged for cash in part or full and is valid for a single transaction only.
                <br />
                These vouchers are not valid during sale or in conjunction with any special promotion.
                Strictly no extension of the expiry date from the date of issue will be allowed.
                The management retains the right to reject any voucher that has been tampered with or found in any way unacceptable.
                <br />
                We are not responsible if a Gift Voucher is lost, stolen, damaged or destroyed and no replacement will be provided in these circumstances.
                <br />
                Vouchers cannot be clubbed and used for single transaction.
                <br />
                This voucher cannot be redeemed to purchase gift cards.
                <br />
                The Gift Card cannot be used for withdrawing cash. The Gift Card is non-negotiable.
                <br />
                The Gift Card will be valid for a period of one (1) year from its date of purchase. The validity of a Gift Card cannot be extended. No new/ replacement Gift Card will be provided in lieu of the expired Gift Card.
                <br />
                Any unused balance in the Gift Card at the end of the one (1) year period will be forfeited.
                The difference in price of products purchased with the Gift Card and the total balance on the Gift Card will remain as unused balance. Subject to these terms and conditions, the customer may use the Gift Card multiple times until the balance amount has been spent.
            </Text>
            <Heading as={"h2"} size={"md"}>SECURITY</Heading>
            <Text>
                Transactions on the Website are secure and protected. Any information entered by the User when transacting on the Website is encrypted to protect the User against unintentional disclosure to third parties. The User's credit and debit card information is not received, stored by or retained by the Company / Website in any manner. This information is supplied by the User directly to the relevant bank/credit card company which are authorized to handle the information provided, and are compliant with the regulations and requirements for making payment from the User’s bank account/credit card.
            </Text>
            <Text>
                The User is requested to refer to the Privacy Policy [insert link] of the Company to know how information is collected and handled by the Company.
            </Text>
            <Heading as={"h2"} size={"md"}>
                USER OBLIGATIONS
            </Heading>
            <Text>
                The User agrees and acknowledges that he/she is a restricted user of this Website, and that he/she:
            </Text>
            <Text>
                a) is bound to not cut, copy, distribute, modify, recreate, reverse engineer, distribute, disseminate, post, publish or create derivative works from, transfer, or sell any information or software obtained from the Website. Any such use / limited use of the Website will only be allowed with the prior express written permission of the Company. For the removal of doubt, it is clarified that any reproduction, copying of the content for commercial or non-commercial purposes and unwarranted modification of data and information contained on the Website is expressly prohibited.
            </Text>
            <Text>
                b) agrees not to access (or attempt to access) the Website and/or the materials or services by any means other than through the interface provided by the Website. The use of deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or its content, or in any way reproduce or circumvent the navigational structure or presentation of the Website, materials or any content, or to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Website will lead to suspension or termination of the User's access to the Website, as detailed in Section 11 herein below. The User acknowledges and agrees that by accessing or using the Website or any of the Services provided thereon, he/she may be exposed to content that he/she may consider offensive, indecent or otherwise objectionable. The Company disclaims any and all liabilities arising in relation to such offensive content on the Website. The User expressly agrees and acknowledges that the properties and/or services displayed on the Website are not owned by the Company/Website, and that the same are the exclusive property of certain third parties (including but not limited to real estate developer) who have chosen to market their properties and/or services through the Company's Website, and that the Company/Website is in no way responsible for the content of the same. The User may however report any such offensive or objectionable content, which the Company may then remove from the Website, at its sole discretion.
            </Text>
            <Text>
                c) In places where Website permits the User to post or upload data/information, the User undertakes to ensure that such material is not offensive or objectionable, and is in accordance with applicable laws. The User expressly agrees that any such material that is deemed to be objectionable/offensive may be removed from the Website immediately and without notice, and further that the User's access to the Website may also be permanently revoked, at the sole discretion of the Company.
            </Text>
            <Text>d) Further undertakes not to:</Text>
            <UnorderedList>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of any other person or entity;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Engage in any activity that interferes with or disrupts access to the Website or the services provided therein (or the servers and networks which are connected to the Website);
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Impersonate any person or entity, or falsely state or otherwise misrepresent his/her affiliation with a person or entity;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Publish, post, disseminate, any information which is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, bigotry or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, harmful to minors, or otherwise unlawful in any manner whatever under any law, rule or regulation currently in force; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Upload or distribute files that contain viruses, trojans, worms, time bombs, corrupted files, or any other similar software or programs that may damage the operation of the Website or that damage, interfere with, intercept or expropriate any system;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Download any file posted/uploaded by another user of the Website that the User is aware, or should reasonably be aware, cannot be legally distributed in such a manner;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Probe, scan or test the vulnerability of the Website or any network connected to the Website, nor breach the security or authentication measures on the Website or any network connected to the Website. The User may not reverse look-up, trace or seek to trace any information relating to any other user of, or visitor to, the Website, or any other customer of the Website, including any user account maintained on the Website but not operated/managed by the User, or exploit the Website or information made available or offered by or through the Website, in any manner;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Disrupt or interfere with the security of, or otherwise cause harm to, the Website, systems resources, accounts, passwords, servers or networks connected to or accessible through the Websites or any affiliated or linked websites;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Collect or store data about other users of the Website.
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Use the Website or any material or content therein for any purpose that is unlawful or prohibited by these Terms, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Website or any other third party(ies);
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Violate any code of conduct or guideline which may be applicable for or to any particular property or Service offered on the Website;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Violate any applicable laws, rules or regulations currently in force within or outside India;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Violate any portion of these Terms or the Policy, including but not limited to any applicable additional terms of the Website contained herein or elsewhere, whether made by amendment, modification, or otherwise;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Threaten the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order, or cause incitement to the commission of any cognizable offence, or prevent the investigation of any offence, or insult any other nation.
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Publish, post, or disseminate information that is false, inaccurate or misleading;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Directly or indirectly offer, attempt to offer, trade, or attempt to trade, any item the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Commit any act that causes the Company to lose (in whole or in part) the services of its internet service provider ("ISP") or in any manner disrupts the services of any other supplier/service provider of the Company/Website;
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    Engage in advertising to, or solicitation of, other users of the Website to buy or sell any products or services not currently displayed on the Website. The User may not transmit any chain letters or unsolicited commercial or junk email/messages to other users via the Website. It shall be a violation of these Terms to use any information obtained from the Website in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another user of the Website without the express prior written consent of the Company.
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    The User hereby expressly authorises the Company/Website to disclose any and all information relating to the User in the possession of the Company/Website to law enforcement or other government officials, as the Company may in its sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those involve personal injury and theft / infringement of intellectual property or for such other purposes and in such other manner as is detailed in the Policy. The User further understands that the Company/Website might be directed to disclose any information (including the identity of persons providing information or materials on the Website) as necessary to satisfy any judicial order, law, regulation or valid governmental request.
                </ListItem>
                <ListItem margin={"10px 0"} fontSize={"sm"}>
                    The User expressly agrees and acknowledges that the Company/Website has no obligation to monitor the materials posted on the Website, but that it has the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms. Notwithstanding this right, the User remains solely responsible for the content of the materials posted on the Website by him/her. In no event shall the Company/Website assume or be deemed to have any responsibility or liability for any content posted, or for any claims, damages or losses resulting from use of any such content and/or the appearance of any content on the Website. The User hereby represents and warrants that he/she has all necessary rights in and to all content provided as well as all information contained therein, and that such content does not infringe any proprietary or other rights of any third party(ies), nor does it contain any libellous, tortuous, or otherwise unlawful or offensive material, and the User hereby accepts full responsibility for any consequences that may arise due to the publishing of any such material on the Website.
                </ListItem>
            </UnorderedList>
            <Heading as={"h2"} size={"md"}>
                Suspension Of User Access And Activity
            </Heading>
            <Text>
                Notwithstanding other legal remedies that may be available to it, the Company may in its sole discretion limit the User's access and/ or activity by immediately removing the User's access credentials either temporarily or indefinitely, or suspend / terminate the User's membership, and/or refuse to provide User with access to the Website, without being required to provide the User with notice or cause:
            </Text>
            <Text>
                If the User is in breach any of these Terms or the Policy or any applicable law for the time being in force;
            </Text>
            <Text>
                If the User has provided wrong, inaccurate, incomplete or incorrect information; and
            </Text>
            <Text>
                If the User's actions may cause any harm, damage or loss to the other users or to the Website/Company, at the sole discretion of the Company.
            </Text>
            <Heading as={"h2"} size={"md"}>
                INDEMNITY AND LIMITATIONS
            </Heading>
            <Text>
                The User hereby expressly agrees to release, defend, indemnify and hold harmless the Website and the Company, its employees, directors, officers, agents and their successors and assigns and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney's fees, caused by or arising out of claims based upon the User's actions or inactions in relation to access and use of the Website and Services, including but not limited to any warranties, representations or undertakings, or in relation to the breach of or the non-fulfilment of any of the User's obligations under these Terms or the Policy, or arising out of the User's infringement of any applicable laws, rules and regulations, including but not limited to infringement of intellectual property rights, payment of statutory dues and taxes, claims of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers, or the infringement of any other rights of a third party.
            </Text>
            <Text>
                In no event shall the Company/Website be liable to compensate the User or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable, and whether or not the Company/Website had been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence or other tortuous action, or any other claim arising out of or in connection with the User's use of or access to the Website and/or the products, services or materials contained therein.
            </Text>
            <Text>
                The limitations and exclusions in this section apply to the maximum extent permitted by applicable law, and the Parties expressly agree that in the event of any statute, rule, regulation or amendment coming into force that would result in the Company/Website incurring any form of liability whatsoever, these Terms and the Policy will stand terminated one (1) day before the coming into effect of such statute, rule, regulation or amendment. It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
            </Text>
            <Heading as={"h2"} size={"md"}>
                INTELLECTUAL PROPERTY RIGHTS
            </Heading>
            <Text>
                Unless expressly agreed to in writing, nothing contained herein shall give the User a right to use any of the Website's trade names, trademarks, service marks, logos, domain names, information, questions, answers, solutions, reports and other distinctive brand features, save according to the provisions of these Terms. All logos, trademarks, brand names, service marks, domain names, including material, designs, and graphics created by and developed by the Website and other distinctive brand features of the Website are the property of the Company. Furthermore, with respect to the Website created by the Company, the Company is the exclusive owner of all the designs, graphics and the like, related to the Website.
            </Text>
            <Text>
                The User shall not use any of the intellectual property displayed on the Website in any manner that is likely to cause confusion among existing or prospective users of the Website, or that in any manner disparages or discredits the Company/Website, to be determined in the sole discretion of the Company. Nothing in these Terms should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any of the Company’s logos or trademarks or trade names or brand names displayed on the Website, without our prior written permission in each instance. All goodwill generated from the use of use of the Company’s name, tradename, trademark, logo or any other intellectual property will inure to our exclusive benefit.
            </Text>
            <Text>
                The User is aware that the Company merely provides a platform through which properties and Services in relation thereto are listed for sale/transfer/lease to the users of the Website. Under no circumstances will the Company be liable in any way for any content or materials of any third parties (including that of Users and campaigners), including, but not limited to, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any such content. The User acknowledges that the Company does not pre-screen content, but that the Company and its designees will have the right (but not the obligation) in their sole discretion to refuse or remove any content that is available via the Services. Without limiting the foregoing, the Company and its designees will have the right to remove any content that violates these Terms or is deemed by the Company, in its sole discretion, to be otherwise objectionable.
            </Text>
            <Text>
                The User is further aware that any reproduction or infringement of the intellectual property of the aforementioned owners by the User will result in legal action being initiated against the User by the respective owners of the intellectual property so reproduced / infringed upon. It is agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
            </Text>
            <Heading as={"h2"} size={"md"}>
                DISCLAIMER OF WARRANTIES AND LIABILITIES
            </Heading>
            <Text>
                a) Except as otherwise expressly stated on the Website, all Services offered on the Website are offered on an "as is" basis without any warranty whatsoever, either express or implied.
            </Text>
            <Text>
                b) The Company/Website makes no representations, express or implied, including without limitation implied warranties of merchantability and fitness of a product or Services for a particular purpose.
            </Text>
            <Text>
                c) This Website, all the properties, materials, information, and Services, included or otherwise made available through this Website are provided without any representation or warranties, express or implied except as otherwise specified in writing. Without prejudice to the foregoing paragraph, the Company does not warrant that:
            </Text>
            <Text>
                this Website will be constantly available, or available at all; or
            </Text>
            <Text>
                the information on this Website is complete, true, accurate or non-misleading, save and except what is directly provided to the User by the Company.
            </Text>
            <Text>
                d) The Company will not be liable to a User in any way or in relation to the contents of, or use of, or otherwise in connection with, the Website. Nothing on the Website constitutes, or is meant to constitute, advice of any kind and is not binding on any Party.
            </Text>
            <Text>
                e) The Users agree and acknowledge that the properties and details thereof (including but not limited to title, location, area and extent, approval and licenses obtained in respect of the property, and amenities attached) as available on the Website are based solely on the information provided by real estate developers, property owners, their brokers or agents. The Company is not responsible for and provides no warranty in respect of the truth, completeness, or accuracy of the same. Any transaction entered or pursued by the User based on the information available on the Website is as per the User’s best and prudent judgment and the Company disclaims all liability in respect of the same.
            </Text>
            <Text>
                f) The Users further agree and acknowledge that the Company and the Website are only facilitators that connect the User with service providers (such as legal and administrative consultants and allied services providers). The Company is not and shall not be liable in any manner whatsoever, for any advice or opinion provided, or any legal documentation created/prepared (including sufficiency of the documents for the intended purpose, contents thereof, admissibility of the documentations in a court of law or enforceability thereof in applicable jurisdictions), goods supplied, or any other services provided (as the case may be) by such service providers. The Company is not liable and makes no representation or warranty with respect to the accuracy or quality of the services provided by such persons and is not responsible for the sufficiency, result, or outcome of any of their views, opinions, or advice.
            </Text>
            <Text>
                g) The User agrees and undertakes that he/she is accessing the Website and transacting at his/her sole risk and are that he/she is using his/her best and prudent judgment before purchasing/leasing or otherwise using any property/ product/service listed on the Website or accessing/using any information displayed thereon.
            </Text>
            <Text>
                h) The Website and the Company accepts no liability for any errors or omissions, whether on behalf of itself or third parties, or for any damage caused to the User, the User's belongings, or any third party, resulting from the use or misuse of any property purchased/leased or Service availed of by the User from the Website.
            </Text>
            <Text>
                i) The Company/Website does not guarantee that (i) the functions and Services contained in the Website will be uninterrupted or error-free, or that the Website or its server will be free of viruses or other harmful components, (ii) the results that may be obtained from the use of the Service will be accurate or reliable, or (iii) the quality of any, property, Services, information, or other materials obtained by a User through the Website will meet his/her expectations, and the User hereby expressly accepts any and all associated risks involved with the User's use of the Website.
            </Text>
            <Text>
                j) Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. Accordingly, some of the limitations set forth above may not apply to certain Users. If a User is dissatisfied with any portion of the Service or with these Terms, the User’s sole and exclusive remedy is to discontinue use of the Website and Service.
            </Text>
            <Text>
                k) The failure of, or delay by, the Company to enforce any right or provision of the Terms or other policies referred to herein, shall not constitute a waiver of such right or provision.
            </Text>
            <Text>
                l) Notwithstanding anything to the contrary contained herein, under no circumstance shall, the liability of the Company to a User exceed the cost paid by such User for the Services.
            </Text>
            <Text>
                m) It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
            </Text>
            <Heading as={"h2"} size={"md"}>THIRD PARTY LINKS</Heading>
            <Text>
                a) The Services may provide or facilitate, or third parties may provide, links or other access to other sites, services and resources on the Internet. The Company has no control over such sites, services and resources and is not responsible for and does not endorse such sites, services and resources.
            </Text>
            <Text>
                b) The Company does not endorse, in any way, any third-party website(s) (including those of its business partners and associates) or content thereof. The Company does not take responsibility or liability for the actions, products, content and services on the websites/online platforms which are linked to the Website or the website/internet platform of its affiliates and/or third-party that use the Website's APIs or otherwise.
            </Text>
            <Text>
                c) The User acknowledges and agrees that the Company will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any content, events, goods, products or services available on or through any such site, service or resource. Any dealings a User has with third parties (including the Company’s business associates and partners such as real estate developers, administrative or legal service providers, financial service/aid/assistance provider including any financial institutions, and allied service providers) found while using the Services are between the User and the third party, and the User agrees that the Company is not liable for any loss or claim that a User may have against any such third party.
            </Text>
            <Text>
                d) The User may enable or log into the Services via various online third-party services, such as social media and social networking services ("Social Networking Services"). However, please remember that the manner in which Social Networking Services use, store and disclose a User’s information is governed solely by the policies of such Social Networking Services, and the Company shall have no liability or responsibility for the privacy practices or other actions of any third-party site or service that may be enabled within the Services.
            </Text>
            <Heading as={"h2"} size={"md"}>
                DISPUTE RESOLUTION AND JURISDICTION
            </Heading>
            <Text>
                It is expressly agreed to by the Parties hereto that the formation, interpretation and performance of these Terms and any disputes arising here from will be resolved through a two-step Alternate Dispute Resolution ("ADR") mechanism. It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
            </Text>
            <Text>
                Mediation: In case of any dispute between the parties, the Parties will attempt to resolve the same amicably amongst themselves, to the mutual satisfaction of both Parties. In the event that the Parties are unable to reach such an amicable solution within thirty (30) days of one Party communicating the existence of a dispute to the other Party, the dispute will be resolved by arbitration, as detailed herein below;
            </Text>
            <Text>
                Arbitration. In the event that the Parties are unable to amicably resolve a dispute by mediation, said dispute will be referred to arbitration by a sole arbitrator to be appointed by the Company, and the award passed by such sole arbitrator will be valid and binding on both Parties. The Parties shall bear their own costs for the proceedings, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be the city of Mumbai in the state of Maharashtra, India.
            </Text>
            <Text>
                The Parties expressly agree that the Terms, Policy and any other agreements entered into between the Parties are governed by the laws, rules and regulations of India, and that the Courts at Mumbai shall have exclusive jurisdiction over any disputes arising between the Parties.
            </Text>
            <Heading as={"h2"} size={"md"}>NOTICES</Heading>
            <Text>
                Any and all communication relating to any dispute or grievance experienced by the User may be communicated to the Company by the User reducing the same to writing, and sending the same to the registered office of the Company by Registered Post Acknowledgement Due / Speed Post Acknowledgement Due (RPAD / SPAD).
            </Text>
            <Heading as={"h2"} size={"md"}>MISCELLANEOUS PROVISIONS</Heading>
            <Text>
                a) Entire Agreement: These Terms, read with the Policy form the complete and final contract between the User and the Company with respect to the subject matter hereof and supersedes all other communications, representations and agreements (whether oral, written or otherwise) relating thereto;
            </Text>
            <Text>
                b) Waiver: The failure of either Party at any time to require performance of any provision of these Terms shall in no manner affect such Party's right at a later time to enforce the same. No waiver by either Party of any breach of these Terms, whether by conduct or otherwise, in any one or more instances, shall be deemed to be or construed as a further or continuing waiver of any such breach, or a waiver of any other breach of these Terms.
            </Text>
            <Text>
                c) Severability: If any provision/clause of these Terms is held to be invalid, illegal or unenforceable by any court or authority of competent jurisdiction, the validity, legality and enforceability of the remaining provisions/clauses of these Terms shall in no way be affected or impaired thereby, and each such provision/clause of these Terms shall be valid and enforceable to the fullest extent permitted by law. In such case, these Terms shall be reformed to the minimum extent necessary to correct any invalidity, illegality or unenforceability, while preserving to the maximum extent the original rights, intentions and commercial expectations of the Parties hereto, as expressed herein.
            </Text>
            <Text>
                d) Assignment: The Company may transfer, sub-contract or otherwise deal with its own rights and/or obligations under the Terms without notifying the User, or without obtaining the User’s consent (except as provided for under the Policy).
            </Text>
            <Text>
                The User may not transfer, sub-contract or otherwise deal with its rights and/or obligations under these Terms, without express written consent from the Company.
            </Text>
            <Text>
                e) Grievance Handling: In the event a User has any grievances, come across any violation of these Terms or becomes aware of any objectionable content on the Website, the User may report the same to the following e-mail id: care@assetorix.com
            </Text>
        </div>
    )
}

export default UserTerm; 
